spring:
  ai:
    openai:
      api-key: ${GROQ_API_KEY}
      base-url: https://api.groq.com/openai
      audio:
        transcription:
          options:
            model: whisper-large-v3
      chat:
        options:
          model: llama-3.3-70b-versatile
  application:
    name: vocash
  datasource:
    url: jdbc:h2:file:${user.home}/.vocash/db;AUTO_SERVER=TRUE
    driver-class-name: org.h2.Driver
    username: sa
    password: ""
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
  servlet:
    multipart:
      max-file-size: 25MB
      max-request-size: 25MB
