spring:
  ai:
    openai:
      api-key: ${GROQ_API_KEY}
      base-url: https://api.groq.com/openai
      audio:
        transcription:
          options:
            model: whisper-large-v3
      chat:
        options:
          model: llama-3.3-70b-versatile
  application:
    name: vocash
  datasource:
    url: jdbc:postgresql://localhost:5432/vocash
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  servlet:
    multipart:
      max-file-size: 25MB
      max-request-size: 25MB
